# -*- coding: utf-8 -*-
"""Q7_pt2_Analise_Exploratoria.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NjU53NVV1LgSTH5ULttIY0PqvI3oUnpp

##**Análise descritiva e exploratória**
"""

#importar o arquivo "Dados_pre_processados"
from google.colab import files
uploaded = files.upload()

"""**Bibliotecas utilizadas**"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""**Importar dados pre processados**"""

dataset = pd.read_csv("Dados_pre_processados.csv")

"""**Gráficos**"""

sns.lmplot('sepal-length', 'sepal-width', data = dataset, fit_reg = False,
           hue = "class", scatter_kws = {"marker": "D", "s": 50})

plt.title('Comprimento da Sépala vs Largura da Sépala')
plt.xlabel("Comprimento da Sépala")
plt.ylabel("Largura da Sépala")

plt.show()

sns.lmplot('petal-length', 'petal-width', data = dataset, fit_reg = False,
           hue = "class", scatter_kws = {"marker": "D", "s": 50})

plt.title('Comprimento da Pétala vs Largura da Pétala')
plt.xlabel("Comprimento da Pétala")
plt.ylabel("Largura da Pétala")

plt.show()

sns.lmplot('sepal-length', 'sepal-width', data = dataset, fit_reg = False,
           hue = "class", scatter_kws = {"marker": "D", "s": 50})

plt.title('Comprimento da Sépala vs Comprimento da Pétala')
plt.xlabel("Comprimento da Sépala")
plt.ylabel("Comprimento da Pétala")

plt.show()

sns.lmplot('sepal-width', 'petal-width', data = dataset, fit_reg = False,
           hue = "class", scatter_kws = {"marker": "D", "s": 50})

plt.title('Largura da Sépala vs Largura da Pétala')
plt.xlabel("Largura da Sépala")
plt.ylabel("Largura da Pétala")

plt.show()

