# -*- coding: utf-8 -*-
"""Q7_pt1_Pre_processamento.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gb_7tgc_Id00yhvFsctQCdXxanCzAXc2

**Questão 7 - Pre Processamento**

A base de dados a ser utilizada será o conjunto de dados IRIS, conjunto de dados muito famoso na análise de dados. Este famoso conjunto de dados apresenta as medidas em centímetros das variáveis comprimento e largura da sépala e comprimento e largura da pétala, respectivamente, para 50 flores de cada uma das 3 espécies de íris. As espécies são Iris setosa, versicolor e virginica.

O objetivo do modelo a ser ajustado é de com base nas medidas fornecidas classificar cada uma das flores como uma das três categorias.
"""

#Importar o arquivo csv chamado "Iris"
from google.colab import files
uploaded = files.upload()

#"""**Bibliotecas e conjunto de dados utilizados**"""

import numpy as np
import pandas as pd

names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
dataset = pd.read_csv("iris.csv", names = names)

dataset.head()

#"""**Verificando o tipo de dados**"""

dataset.dtypes

#"""**Verificando duplicatas de dados**"""

duplicatas = dataset[dataset.duplicated()]
print(duplicatas.shape)
duplicatas.head()

dataset.drop_duplicates(inplace=True)
dataset.shape

#"""**Verificando valores nulos (missing)**"""

dataset.isnull().values.any()

print(dataset.isna().sum())
print(f'\nTotal de valores missing: {dataset.isna().sum().sum()}')

# """**Salvando o banco de dados após pre-processamento**"""

dataset.to_csv('Dados_pre_processados.csv', index = False)
dataset

files.download('Dados_pre_processados.csv')

